version: '3'
services:
  php-apache:
    image: php:8.2.0-apache
    ports:
      - 8080:80
    volumes:
      - ./src/index.php:/var/www/html/index.php
    command: 
      - /bin/sh
      - -c
      - >
        echo "App is ready on http://localhost:80" &&
        apache2-foreground
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: test
      MYSQL_PASSWORD: test